### ISSUE TITLE
Issue continuing training from checkpoint

### ISSUE THREAD

**Issue by wtheisen** [clip-italian/clip-italian#25]
Hello, I have trained a model for 40 epochs. I tried to use the `--run_from_checkpoint ./40` on another run to train the model for another 40 epochs but I'm receiving the following error:

```
`text_config` is `None`. Initializing the `CLIPTextConfig` with default values.
`vision_config` is `None`. initializing the `CLIPVisionConfig` with default values.
loading weights file ./40/flax_model.msgpack
Traceback (most recent call last):
  File "./run_hybrid_clip.py", line 837, in <module>
    main()
  File "./run_hybrid_clip.py", line 532, in main
    model = FlaxHybridCLIP.from_pretrained(
  File "/media/wtheisen/scratch1/clip_multi_base/venv/lib/python3.8/site-packages/transformers/modeling_flax_utils.py", line 820, in from_pretrained
    c
  File "/home/wtheisen/Programs/Python/clip-italian/hybrid_clip/modeling_hybrid_clip.py", line 148, in __init__
    module = self.module_class(config=config, dtype=dtype, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_do_init'
```

I tried removing the _do_init argument from the following line:
`model = cls(config, *model_args, _do_init=_do_init, **model_kwargs)`
which allows the code to run successfully but it seems to have lost most of the progress I made in the earlier trainings making me think that it didn't successfully load from the checkpoint. Thank you.

**Comment by lakatosgabor** [comment]
@wtheisen 
I think two solutions: 
first: https://github.com/clip-italian/clip-italian/issues/27#issuecomment-1800443339
second: delete this varriable "**model_kwargs" and run without this parameter
