### ISSUE TITLE
ERORR: "Missing XLA Configuration" while running the script?

### ISSUE THREAD

**Issue by karndeepsingh** [clip-italian/clip-italian#9]
Hi,
I was trying to train the clip model on the images and text and used run_hybrid_clip.py script to train but got following error. Please help me to remove the following error. I am trying to train it on GPU device, it seems that error is due to torch_xla which is on TPU. Please help me to train it on GPU.
```
!python run_hybrid_clip.py \
    --output_dir ${MODEL_DIR} \
    --text_model_name_or_path="/home/jupyter/HUSE/sentence_similarity_spanish_es" \
    --vision_model_name_or_path="openai/clip-vit-base-patch32" \
    --tokenizer_name="sentence_similarity_spanish_es" \
    --train_file="./train_dataset.json" \
    --validation_file="./valid_dataset.json" \
    --do_train --do_eval \
    --num_train_epochs="40" --max_seq_length 512 \
    --per_device_train_batch_size="64" \
    --per_device_eval_batch_size="64" \
    --learning_rate="5e-5" --warmup_steps="0" --weight_decay 0.1 \
    --overwrite_output_dir \
    --preprocessing_num_workers 32 \

```

```
comet_ml is installed but `COMET_API_KEY` is not set.
Traceback (most recent call last):
  File "run_hybrid_clip.py", line 832, in <module>
    main()
  File "run_hybrid_clip.py", line 472, in main
    ) = parser.parse_args_into_dataclasses()
  File "/opt/conda/lib/python3.7/site-packages/transformers/hf_argparser.py", line 214, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 101, in __init__
  File "/opt/conda/lib/python3.7/site-packages/transformers/training_args.py", line 1066, in __post_init__
    and (self.device.type != "cuda")
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/import_utils.py", line 829, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/training_args.py", line 1357, in device
    return self._setup_devices
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/generic.py", line 49, in __get__
    cached = self.fget(obj)
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/import_utils.py", line 829, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/training_args.py", line 1299, in _setup_devices
    device = xm.xla_device()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 232, in xla_device
    devkind=devkind if devkind is not None else None)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 137, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 19, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/computation_client.cc:273 : Missing XLA configuration

```

**Comment by g8a9** [comment]
Hi! It seems you have a configuration issue with your machine.

Can you import/use JAX properly outside of our script?
What kind of accelerator are you using? Is it a TPU or GPU? Or none?

**Comment by karndeepsingh** [comment]
> Hi! It seems you have a configuration issue with your machine.
> 
> Can you import/use JAX properly outside of our script? What kind of accelerator are you using? Is it a TPU or GPU? Or none?

Hi @g8a9 ,

Yes, I am able to import JAX outside the script.
I am using GPU (NVIDIA TESLA T4 ) in GCP VM. And wanted to use train the model using GPU. Please guide me with required changes.

Thanks

**Comment by g8a9** [comment]
Hi, as I read in #10 you managed to configure the GCP VM and launch the training on GPU.
